
//Get user by ID
GET http://localhost:8080/stream/User/1
//works
###
//add new user // returns 200 OK if successfully added
POST http://localhost:8080/stream/User
Content-Type: application/json

{
  "fname" : "TestUser2",
  "lname" : "TestUser2Name",
  "Image" : "ImageLink",
  "password": "totallySave",
  "email" : "test23@gmail.com"
}
//works
###

// login using password and email

POST http://localhost:8080/stream/Login
Content-Type: application/json

{
"email" : "test23@gmail.com",
"password": "totalySave"
}
//works
###

// add Company
POST http://localhost:8080/stream/Company
Content-Type: application/json

{
"name": "company name 2"
}
###
//get single Company by id
GET http://localhost:8080/stream/Company/0
###
//Get all Companies
GET http://localhost:8080/stream/Company
###
//Get all series
GET http://localhost:8080/stream/Series/all
###
// add series
POST http://localhost:8080/stream/Series
Content-Type: application/json

{
"image" : "imageLink",
"name" : "SeriesNameNew",
  "description": "text",
  "airdate": "2020-02-20",
  "companyid": 0,
  "genreid": 1,
  "rating": 4
}

###
//get single series

GET http://localhost:8080/stream/Series/1

###
//Get all episodes of one series
GET  http://localhost:8080/stream/Series/1/Episodes

###
// Get episode by ID
GET http://localhost:8080/stream/Episode/1

###

POST  http://localhost:8080/stream/Series/1/Episode
Content-Type: application/json

{
  "name": "Name of episode",
  "description": "desc",
  "videolink": "videolink"
}

###
//Get all Genres
GET  http://localhost:8080/stream/Genre

###
// Get all Series of a Genre
GET http://localhost:8080/stream/Genre/1/Series

###
//add Genre
POST http://localhost:8080/stream/Genre
Content-Type: application/json

{
  "name": "Genre Name"
}

###
// get all bookmarked shows for a User
GET http://localhost:8080/stream/Bookmark/1

###
//Check if a series has been bookmarked returns true if it isnt returns true if it is
// GET http://localhost:8080/stream/Bookmark/{{userID}}/{{seriesID}}
GET http://localhost:8080/stream/Bookmark/1/1

###
//Bookmark or umbookmark a show returns true if it has been bookmarked returns false if it has been unbookmarked
//POST http://localhost:8080/stream/Bookmark/{{userID}}/{{seriesID}}
POST http://localhost:8080/stream/Bookmark/1/1

###
//Get all watched Episodes of a User

GET http://localhost:8080/stream/Watchlist/1

###
//Get all watched episodes of a Series
//GET https://localhost:8080/stream/Series/Watchlist/{{userID}}/{{SeriesID}}
GET http://localhost:8080/stream/Series/Watchlist/1/1

###
// add to Watchlist returns true or false
//POST http://localhost:8080/stream/WatchList/{{userID}}/{{EpisodeID}}
POST http://localhost:8080/stream/WatchList/1/1

###
//check if a episode has been watched returns true or false
// GET https://localhost:8080/stream/hasWatched/{{userID}}/{{EpisodeID}}
GET http://localhost:8080/stream/hasWatched/1/1

###
// add a Comment
POST http://localhost:8080/stream/Comment
Content-Type: application/json

{
  "UID": 1,
  "SID": 1,
  "comments": "This is a comment"
}

###
//Get Comments by SeriesID
GET http://localhost:8080/stream/Comments/1

###
//get LoginInfo

GET http://localhost:8080/stream/LoginInfo